# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
ignore %r{^ignored/path/}, /build/
guard 'shell' do
  watch(/(.*).cpp/) do |m|
    system('cd build && cmake .. && make')
  end
end
